src/main/java/dev/bene/doodle/model/Info.java
package dev.bene.doodle.model;

import dev.bene.doodle.MongoDB;

import org.bson.Document;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.NoSuchAlgorithmException;
import java.util.*;
import java.text.SimpleDateFormat;
import java.util.stream.Collectors;

public class Info {
    private String id_public;
    private String id_private;
    private String roomName;
    private String participantName;
    private String searchPublic;
    private String searchPrivate;
    private String date;
    private String from;
    private String to;
    private Room room;
    private List<People> participants;
    private String comment;
    private final MongoDB mongoDB;
    private final SimpleDateFormat dateFormatHHMM = new SimpleDateFormat("HH:mm");
    private final SimpleDateFormat dateFormatYYYYMMDD = new SimpleDateFormat("yyyy-MM-dd");

    public Info() {
        mongoDB = new MongoDB();
        participants = new ArrayList<>();

        init();
    }

    public void init() {
        date = dateFormatYYYYMMDD.format(new Date());
        from = dateFormatHHMM.format(new Date());
        to = dateFormatHHMM.format(new Date(new Date().getTime() + 180 * 60 * 1000));

        comment = "-";
        searchPrivate = "Private key";
        searchPublic = "Public key";

        try {
            KeyPair keyPair = KeyPairGenerator.getInstance("RSA").generateKeyPair();
            Base64.Encoder enc = Base64.getEncoder();
            id_private = new String(enc.encode(keyPair.getPrivate().getEncoded()));
            id_public = new String(enc.encode(keyPair.getPublic().getEncoded()));
        } catch (NoSuchAlgorithmException e) {
            System.err.println("RSA is not a know generator");
        }
    }



    public String getSearchPublic() {
        return searchPublic;
    }

    public void setSearchPublic(String searchPublic) {
        this.searchPublic = searchPublic;
    }

    public String getSearchPrivate() {
        return searchPrivate;
    }

    public void setSearchPrivate(String searchPrivate) {
        this.searchPrivate = searchPrivate;
    }

    public String getRoomName() {
        return roomName;
    }

    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    public String getParticipantName() {
        return participantName;
    }

    public void setParticipantName(String participantName) {
        this.participantName = participantName;
    }

    public String getId_public() {
        return id_public;
    }

    public void setId_public(String id_public) {
        this.id_public = id_public;
    }

    public String getId_private() {
        return id_private;
    }

    public void setId_private(String id_private) {
        this.id_private = id_private;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getTo() {
        return to;
    }

    public void setTo(String to) {
        this.to = to;
    }

    public List<People> getParticipants() {
        return participants;
    }

    public void setParticipants(List<People> participants) {
        this.participants = participants;
    }

    public void setParticipants(ArrayList<People> participants) {
        this.participants = participants;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Room getRoom() {
        return room;
    }

    public void setRoom(Room room) {
        this.room = room;
    }

    public Document toBson() {
        try {
            Document doc = new Document();
            doc.append("reservation", true);
            doc.append("id_public", id_public);
            doc.append("id_private", id_private);
            doc.append("date", date);
            doc.append("from", from);
            doc.append("to", to);
            doc.append("room", room != null ? room.toString() : "");
            doc.append("participants", participants.toString());
            doc.append("comment", comment);
            return doc;
        } catch (Exception e) {
            System.err.println("Error while creating BSON");
            return null;
        }
    }


    public boolean fromBSON(Document doc) {
        try {
            final String participantsString = doc.getString("participants");
            participants = Arrays.stream(participantsString.substring(1, participantsString.length() - 1).split(",")).map(People::new).collect(Collectors.toList());
            id_public = doc.getString("id_public");
            id_private = doc.getString("id_private");
            date = doc.getString("date");
            from = doc.getString("from");
            to = doc.getString("to");
            room = new Room(doc.getString("room"));
            comment = doc.getString("comment");
            return true;
        } catch (Exception e) {
            System.err.println("Error while parsing BSON");
            return false;
        }
    }
}

src/main/java/dev/bene/doodle/model/People.java
package dev.bene.doodle.model;

import java.util.Objects;

public class People {
    private String name;

    public People() {
    }

    public People(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString(){
    	return name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof People)) return false;
        People people = (People) o;
        return Objects.equals(getName(), people.getName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getName());
    }
}

src/main/java/dev/bene/doodle/model/Room.java
package dev.bene.doodle.model;

import java.util.Objects;

public class Room {
    private String name;

    public Room(String name) {
        this.name = name;
    }

    public Room() {
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Room)) return false;
        Room room = (Room) o;
        return Objects.equals(getName(), room.getName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getName());
    }

    @Override
    public String toString() {
        return name;
    }
}

src/main/java/dev/bene/doodle/controller/InfoBean.java
package dev.bene.doodle.controller;

import dev.bene.doodle.MongoDB;
import dev.bene.doodle.model.Info;
import dev.bene.doodle.model.People;
import dev.bene.doodle.model.Room;

import com.mongodb.client.FindIterable;
import org.bson.Document;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.util.ArrayList;
import java.util.List;

@ManagedBean
@ViewScoped
public class InfoBean {
    private final MongoDB mongoDB;
    private Info info;

    public InfoBean() {
        mongoDB = new MongoDB();
        info = new Info();
    }

    public Info getInfo() {
        return info;
    }

    public void setInfo(Info info) {
        this.info = info;
    }

    public List<Room> getAllRooms() {
        List<Room> rooms = new ArrayList<>();
        FindIterable<Document> roomNames = mongoDB.getCollectionRooms();
        for (Document roomName : roomNames) {
            String roomNameString = roomName.getString("roomName");
            rooms.add(new Room(roomNameString));
        }
        return rooms;
    }

    public List<People> getAllParticipants() {
        List<People> participants = new ArrayList<>();
        FindIterable<Document> participantNames = mongoDB.getCollectionParticipant();
        for (Document participantName : participantNames) {
            String participantNameString = participantName.getString("participantName");
            participants.add(new People(participantNameString));
        }
        return participants;
    }

    public String submitRoom() {
        mongoDB.setRoom(info.getRoomName());
        return "index.xhtml?faces-redirect=true";
    }

    public String submitParticipant() {
        mongoDB.setParticipant(info.getParticipantName());
        return "index.xhtml?faces-redirect=true";
    }

}

src/main/java/dev/bene/doodle/controller/ReservationBean.java
package dev.bene.doodle.controller;

import dev.bene.doodle.model.Info;
import dev.bene.doodle.MongoDB;

import org.bson.Document;
import com.mongodb.client.FindIterable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean
@SessionScoped
public class ReservationBean {

    private Info info;
    private final MongoDB mongoDB;


    public ReservationBean() {
        info = new Info();
        mongoDB = new MongoDB();
    }

    public Info getInfo() {
        return info;
    }

    public void setInfo(Info info) {
        this.info = info;
    }

    public FindIterable<Document> getCollectionEvents() {
        return mongoDB.getCollectionEvents();
    }

    public String submit() {
        mongoDB.setCollection(info.toBson());
        return "secrets.xhtml";
    }

    public String add() {
        info = new Info();
        return "add.xhtml?faces-redirect=true";
    }

    public String delete(String id) {
        mongoDB.removeCollection(id);
        return "index.xhtml?faces-redirect=true";
    }

    public String update(String id) {
        mongoDB.updateCollection(info.toBson(), id);
        return "edit.xhtml?faces-redirect=true";
    }

    public String editPrivate(String id) {
        info = new Info();

        if (!info.fromBSON(mongoDB.getReservationByPrivateID(id))) {
            return "error.xhtml";
        } else {
            Document doc = mongoDB.getReservationByPrivateID(id);
            info.fromBSON(doc);
            return "edit.xhtml?faces-redirect=true";
        }
    }

    public String viewPublic(String id) {
        info = new Info();

       if (!info.fromBSON(mongoDB.getReservationByPublicID(id))) {
           return "error.xhtml";
       } else {
           Document doc = mongoDB.getReservationByPublicID(id);
           info.fromBSON(doc);
           return "view.xhtml?faces-redirect=true";
       }
    }
}

src/main/webapp/add.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Created by IntelliJ IDEA.
  User: lukaswigger
  Date: 14.05.23
  Time: 14:47
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:p="http://primefaces.org/ui">

<h:head>
   <link rel="stylesheet" href="css/tail-wind.css" />
   <link rel="stylesheet" href="css/tailwind.css" />
   <title>Add Reservation - Doodle</title>
</h:head>

<h:body class="bg-gray-900">
   <div class="lg:grid lg:min-h-screen lg:grid-cols-12">
      <div class="relative block h-16 lg:order-last lg:col-span-5 lg:h-full xl:col-span-3">
         <img alt="Benedict-Classroom" src="img/bene.png" class="absolute inset-0 h-full w-full object-cover"/>
      </div>
      <div class="px-8 py-8 sm:px-12 lg:col-span-7 lg:py-12 lg:px-16 xl:col-span-9">
         <div class="max-w-xl lg:max-w-4xl">
            <h:link outcome="index" class="block text-blue-600">← Back</h:link>
            <h1 class="mt-6 text-2xl font-bold text-white sm:text-3xl md:text-4xl">Add Reservation</h1>
            <h:form class="max-w-xl">
               <div class="col-span-6 sm:col-span-4 my-1 mt-4">
                  <h:outputLabel for="date" value="Date: " class="block text-gray-300  text-sm font-bold mb-2" />
                  <h:inputText id="date" value="#{reservationBean.info.date}" class="border-gray-200 text-sm placeholder-gray-500 shadow-sm border-gray-700 bg-gray-800 text-white outline-none appearance-none border border-transparent rounded w-full p-2  text-white leading-normal appearance-none focus:outline-none  focus:bg-gray-800 focus:border-gray-300 focus:border-gray-500 focus:text-white"/>
               </div>
               <div class="col-span-6 sm:col-span-4 my-1">
                  <h:outputLabel for="from" value="From: " class="block text-gray-300  text-sm font-bold mb-2" />
                  <h:inputText id="from" value="#{reservationBean.info.from}" type="time" class="border-gray-200 text-sm placeholder-gray-500 shadow-sm border-gray-700 bg-gray-800 text-white outline-none appearance-none border border-transparent rounded w-full p-2  text-white leading-normal appearance-none focus:outline-none  focus:bg-gray-800 focus:border-gray-300 focus:border-gray-500 focus:text-white" />
               </div>
               <div class="col-span-6 sm:col-span-4 my-1">
                  <h:outputLabel for="to" value="To: " class="block text-gray-300  text-sm font-bold mb-2" />
                  <h:inputText id="to" value="#{reservationBean.info.to}" type="time" class="border-gray-200 text-sm placeholder-gray-500 shadow-sm border-gray-700 bg-gray-800 text-white outline-none appearance-none border border-transparent rounded w-full p-2  text-white leading-normal appearance-none focus:outline-none  focus:bg-gray-800 focus:border-gray-300 focus:border-gray-500 focus:text-white" />
               </div>
               <div class="col-span-6 sm:col-span-4 my-1">
                  <h:outputLabel for="room" value="Room: " class="block text-gray-300  text-sm font-bold mb-2" />
                  <h:selectOneListbox id="room" value="#{infoBean.info.room}" converter="roomConverter" class="border-gray-200 text-sm placeholder-gray-500 shadow-sm border-gray-700 bg-gray-800 text-white outline-none appearance-none border border-transparent rounded w-full p-2  text-white leading-normal appearance-none focus:outline-none  focus:bg-gray-800 focus:border-gray-300 focus:border-gray-500 focus:text-white">
                     <f:selectItems value="#{infoBean.allRooms}" />
                  </h:selectOneListbox>
               </div>
               <div class="col-span-6 sm:col-span-4 my-1">
                  <h:outputLabel for="participants" value="Participants: " class="block text-gray-300  text-sm font-bold mb-2" />
                  <h:selectManyListbox id="participants" value="#{infoBean.info.participants}" class="border-gray-200 text-sm placeholder-gray-500 shadow-sm border-gray-700 bg-gray-800 text-white outline-none appearance-none border border-transparent rounded w-full p-2  text-white leading-normal appearance-none focus:outline-none  focus:bg-gray-800 focus:border-gray-300 focus:border-gray-500 focus:text-white">
                     <f:selectItems value="#{infoBean.allParticipants}" />
                  </h:selectManyListbox>
               </div>
               <div class="col-span-6 sm:col-span-4 my-1 my-2">
                  <h:outputLabel for="comment" value="Comment: " class="block text-gray-300  text-sm font-bold mb-2" />
                  <h:inputTextarea id="comment" value="#{reservationBean.info.comment}" class="border-gray-200 text-sm placeholder-gray-500 shadow-sm border-gray-700 bg-gray-800 text-white outline-none appearance-none border border-transparent rounded w-full p-2  text-white leading-normal appearance-none focus:outline-none  focus:bg-gray-800 focus:border-gray-300 focus:border-gray-500 focus:text-white" />
               </div>
               <h:commandButton value="Submit" id="submit" action="#{reservationBean.submit()}" class="my-4 inline-block shrink-0 h-12 rounded-md border border-blue-600 bg-blue-600 px-12 py-3 text-sm font-medium text-white transition hover:bg-transparent focus:outline-none focus:ring active:text-blue-500 hover:bg-blue-700 hover:text-white" />
            </h:form>
         </div>
      </div>
   </div>
</h:body>

</html>

src/main/webapp/addPeople.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Created by IntelliJ IDEA.
  User: lukaswigger
  Date: 14.05.23
  Time: 14:47
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui">

<h:head>
    <link rel="stylesheet" href="css/tail-wind.css" />
    <link rel="stylesheet" href="css/tailwind.css" />
    <title>Add People - Doodle</title>
</h:head>

<h:body class="bg-gray-900">
    <div class="lg:grid lg:min-h-screen lg:grid-cols-12">
        <div class="relative block h-16 lg:order-last lg:col-span-5 lg:h-full xl:col-span-3">
            <img alt="Benedict-Classroom" src="img/bene.png" class="absolute inset-0 h-full w-full object-cover"/>
        </div>
        <div class="px-8 py-8 sm:px-12 lg:col-span-7 lg:py-12 lg:px-16 xl:col-span-9">
            <div class="max-w-xl lg:max-w-4xl">
                <h:link outcome="index" class="block text-blue-600">← Back</h:link>
                <h1 class="mt-6 text-2xl font-bold text-white sm:text-3xl md:text-4xl">Add People</h1>
                <h:form class="max-w-xl">
                    <div class="col-span-6 sm:col-span-4 my-1 mt-4">
                        <h:outputLabel for="name" value="Name: " class="block text-gray-300  text-sm font-bold mb-2" />
                        <p:inputText id="name" value="#{infoBean.info.participantName}" required="true" class="border-gray-200 text-sm placeholder-gray-500 shadow-sm border-gray-700 bg-gray-800 text-white outline-none appearance-none border border-transparent rounded w-full p-2  text-white leading-normal appearance-none focus:outline-none  focus:bg-gray-800 focus:border-gray-300 focus:border-gray-500 focus:text-white"/>
                    </div>
                    <br/>
                    <p:commandButton value="Submit" id="submit" action="#{infoBean.submitParticipant()}" update="@form" class="my-4 inline-block shrink-0 h-12 rounded-md border border-blue-600 bg-blue-600 px-12 py-3 text-sm font-medium text-white transition hover:bg-transparent focus:outline-none focus:ring active:text-blue-500 hover:bg-blue-700 hover:text-white" />
                </h:form>
            </div>
        </div>
    </div>
</h:body>

</html>

src/main/webapp/addRoom.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Created by IntelliJ IDEA.
  User: lukaswigger
  Date: 14.05.23
  Time: 14:47
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui">

<h:head>
    <link rel="stylesheet" href="css/tail-wind.css" />
    <link rel="stylesheet" href="css/tailwind.css" />
    <title>Add Room - Doodle</title>
</h:head>

<h:body class="bg-gray-900">
    <div class="lg:grid lg:min-h-screen lg:grid-cols-12">
        <div class="relative block h-16 lg:order-last lg:col-span-5 lg:h-full xl:col-span-3">
            <img alt="Benedict-Classroom" src="img/bene.png" class="absolute inset-0 h-full w-full object-cover"/>
        </div>
        <div class="px-8 py-8 sm:px-12 lg:col-span-7 lg:py-12 lg:px-16 xl:col-span-9">
            <div class="max-w-xl lg:max-w-4xl">
                <h:link outcome="index" class="block text-blue-600">← Back</h:link>
                <h1 class="mt-6 text-2xl font-bold text-white sm:text-3xl md:text-4xl">Add Room</h1>
                <h:form class="max-w-xl">
                    <div class="col-span-6 sm:col-span-4 my-1 mt-4">
                        <h:outputLabel for="name" value="Room: " class="block text-gray-300  text-sm font-bold mb-2" />
                        <p:inputText id="name" value="#{infoBean.info.roomName}" required="true" class="border-gray-200 text-sm placeholder-gray-500 shadow-sm border-gray-700 bg-gray-800 text-white outline-none appearance-none border border-transparent rounded w-full p-2  text-white leading-normal appearance-none focus:outline-none  focus:bg-gray-800 focus:border-gray-300 focus:border-gray-500 focus:text-white"/>
                    </div>
                    <br/>
                    <p:commandButton value="Submit" id="submit" action="#{infoBean.submitRoom()}" update="@form" class="my-4 inline-block shrink-0 h-12 rounded-md border border-blue-600 bg-blue-600 px-12 py-3 text-sm font-medium text-white transition hover:bg-transparent focus:outline-none focus:ring active:text-blue-500 hover:bg-blue-700 hover:text-white" />
                </h:form>
            </div>
        </div>
    </div>
</h:body>

</html>

src/main/webapp/edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Created by IntelliJ IDEA.
  User: Elin
  Date: 14.05.23
  Time: 14:47
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core">

<h:head>
    <link rel="stylesheet" href="css/tail-wind.css" />
    <link rel="stylesheet" href="css/tailwind.css" />
    <title>Edit Reservation - Doodle</title>
</h:head>
<h:body class="bg-gray-900">
    <div class="lg:grid lg:min-h-screen lg:grid-cols-12">
        <div class="relative block h-16 lg:order-last lg:col-span-5 lg:h-full xl:col-span-3">
            <img alt="Benedict-Classroom" src="img/bene.png" class="absolute inset-0 h-full w-full object-cover"/>
        </div>
        <div class="px-8 py-8 sm:px-12 lg:col-span-7 lg:py-12 lg:px-16 xl:col-span-9">
            <div class="max-w-xl lg:max-w-4xl">
                <h:link outcome="index" class="block text-blue-600">← Back</h:link>
                <h1 class="mt-6 text-2xl font-bold text-white sm:text-3xl md:text-4xl">Edit Reservation</h1>
                <h:form class="max-w-xl">
                    <div class="col-span-6 sm:col-span-4 my-1 mt-4">
                        <h:outputLabel for="date" value="Date:" class="block text-gray-300 text-sm font-bold mb-2" />
                        <h:inputText value="#{reservationBean.info.date}" id="date" class="border-gray-200 text-sm placeholder-gray-500 shadow-sm border-gray-700 bg-gray-800 text-white outline-none appearance-none border border-transparent rounded w-full p-2  text-white leading-normal appearance-none focus:outline-none  focus:bg-gray-800 focus:border-gray-300 focus:border-gray-500 focus:text-white" aria-placeholder="date"  />
                    </div>
                    <div class="col-span-6 sm:col-span-4 my-1">
                        <h:outputLabel for="from" value="From:" class="block text-gray-300 text-sm font-bold mb-2" />
                        <h:inputText value="#{reservationBean.info.from}" id="from" class="border-gray-200 text-sm placeholder-gray-500 shadow-sm border-gray-700 bg-gray-800 text-white outline-none appearance-none border border-transparent rounded w-full p-2  text-white leading-normal appearance-none focus:outline-none  focus:bg-gray-800 focus:border-gray-300 focus:border-gray-500 focus:text-white" aria-placeholder="from"/>
                    </div>
                    <div class="col-span-6 sm:col-span-4 my-1">
                        <h:outputLabel for="to" value="To:" class="block text-gray-300 text-sm font-bold mb-2" />
                        <h:inputText value="#{reservationBean.info.to}" id="to" class="border-gray-200 text-sm placeholder-gray-500 shadow-sm border-gray-700 bg-gray-800 text-white outline-none appearance-none border border-transparent rounded w-full p-2  text-white leading-normal appearance-none focus:outline-none  focus:bg-gray-800 focus:border-gray-300 focus:border-gray-500 focus:text-white" aria-placeholder="to" />
                    </div>
                    <div class="col-span-6 sm:col-span-4 my-1">
                        <h:outputLabel for="room" value="Room:" class="block text-gray-300 text-sm font-bold mb-2" />
                        <h:selectOneListbox id="room" value="#{reservationBean.info.room}" converter="roomConverter" class="border-gray-200 text-sm placeholder-gray-500 shadow-sm border-gray-700 bg-gray-800 text-white outline-none appearance-none border border-transparent rounded w-full p-2  text-white leading-normal appearance-none focus:outline-none  focus:bg-gray-800 focus:border-gray-300 focus:border-gray-500 focus:text-white">
                            <f:selectItems value="#{infoBean.allRooms}" />
                        </h:selectOneListbox>
                    </div>
                    <div class="col-span-6 sm:col-span-4 my-1">
                        <h:outputLabel for="participants" value="Participants: " class="block text-gray-300  text-sm font-bold mb-2" />
                        <h:selectManyListbox id="participants" value="#{reservationBean.info.participants}" class="border-gray-200 text-sm placeholder-gray-500 shadow-sm border-gray-700 bg-gray-800 text-white outline-none appearance-none border border-transparent rounded w-full p-2  text-white leading-normal appearance-none focus:outline-none  focus:bg-gray-800 focus:border-gray-300 focus:border-gray-500 focus:text-white">
                            <f:selectItems value="#{infoBean.allParticipants}" />
                        </h:selectManyListbox>
                    </div>
                    <div class="col-span-6 sm:col-span-4 my-1 my-2">
                        <h:outputLabel for="comment" value="Comment:" class="block text-gray-300 text-sm font-bold mb-2" />
                        <h:inputTextarea value="#{reservationBean.info.comment}" id="comment" class="border-gray-200 text-sm placeholder-gray-500 shadow-sm border-gray-700 bg-gray-800 text-white outline-none appearance-none border border-transparent rounded w-full p-2  text-white leading-normal appearance-none focus:outline-none  focus:bg-gray-800 focus:border-gray-300 focus:border-gray-500 focus:text-white"  aria-placeholder="comment"/>
                    </div>
                    <h:commandButton value="Update" id="update" action="#{reservationBean.update(reservationBean.info.id_private)}" class="inline-block h-12 rounded-md border border-blue-600 bg-blue-600 px-12 py-3 text-sm font-medium text-white transition hover:bg-transparent focus:outline-none focus:ring active:text-blue-500 hover:bg-blue-700 hover:text-white mr-2">
                        <f:param name="id" value="#{reservationBean.info.id_private}" />
                    </h:commandButton>
                    <h:commandButton value="Delete" id="delete" action="#{reservationBean.delete(reservationBean.info.id_private)}" class="inline-block h-12 rounded-md border border-red-700 bg-red-700 px-12 py-3 text-sm font-medium text-white transition hover:bg-transparent focus:outline-none focus:ring active:text-red-500 hover:bg-red-800 hover:text-white">
                        <f:param name="id" value="#{reservationBean.info.id_private}" />
                    </h:commandButton>
                </h:form>
            </div>
        </div>
    </div>
</h:body>
</html>